import { describe, expect, test } from '@jest/globals';
import { jwtDecode } from './jwtDecode';

describe('jwtDecode', () => {
  test('jwtDecode decodes jwt', () => {
    // JWT Generated by https://www.javainuse.com/jwtgenerator
    const decoded = jwtDecode(
      'eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoidGVzdCIsImlkIjoidGVzdCIsImV4cCI6MTczNTMxNTIwMCwiaWF0IjoxNzM1MzExNjAwfQ.eHE8ejVMWgv61FoRvigAMyoybyuCTQIKj1XX6UgyABE',
    );

    // JWTs give exp in seconds, Date().getTime() gives in ms
    const jwtExp = Math.floor(new Date('2024-12-27T16:00:00.000Z').getTime() / 1000);

    expect(decoded).toHaveProperty('name');
    expect(decoded.name).toEqual('test');
    expect(decoded).toHaveProperty('id');
    expect(decoded.id).toEqual('test');
    expect(decoded).toHaveProperty('exp');
    expect(decoded.exp).toBe(jwtExp);
  });
});
