# from https://biomejs.dev/recipes/continuous-integration/
name: Frontend| Format & Lint

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: 
        run: cd frontend && biome ci ./src
