# from https://biomejs.dev/recipes/continuous-integration/
name: Server| unit test

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
        id: go

      - name: Install dependencies
        run: |
          go get -v -t -d ./...        

      - name: Run unit tests
        env:
        run: go test -v ./...
