name: Server| unit test

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  tester:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server/

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
        id: go

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Run unit tests
        run: go test -v ./...
